export const statusCode = {
    STATUS_CODE_OK : 200,
    STATUS_CODE_CREATED : 201,
    STATUS_CODE_BAD_REQUEST : 400,
    STATUS_CODE_NOT_FOUND : 404,
    STATUS_CODE_WRONG : 403,
    STATUS_CODE_UNAUTHORISED : 401,
    STATUS_CODE_CONFLICT : 409,
    STATUS_CODE_ERROR : 500
}